project:
  type: website
  output-dir: docs

website:
  site-url: https://maelle.github.io/babelsite/
  repo-url: https://github.com/maelle/babelsite
  repo-actions: [edit, issue]
  title: "babelsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css




babelquarto:
  languagecodes:
  - name: fr
    text: "Causons fran√ßais"
  - name: en
    text: "Shakespeare's language"
  mainlanguage: 'en'
  languages: ['fr']
title-fr: title in fr
description-fr: description in fr
author-fr: author in fr
lang: en
